site_name: Entrada Documentation
repo_url: https://github.com/EntradaProject
theme: readthedocs
pages:
- 'Home': 'index.md'
- 'Reporting Issues': 'about/reporting-issues.md'
- 'Administrator Documentation':
    - 'Server Requirements': 'administrator/server-requirements.md'
    - 'Application Server': 'administrator/application-server.md'
    - 'Database Server': 'administrator/database-server.md'
- 'Developer Documentation':
    - 'Getting Started': 'developer/getting-started.md'
    - 'Overview': 'developer/overview.md'
    - 'Contributions': 'developer/contributions.md'
    - 'Quickstart Guide': 'developer/quickstart.md'
    - 'Entrada Walkthrough': 'developer/walkthrough.md'
    - 'Coding Standards': 'developer/standards.md'
    - 'Database': 'developer/database.md'
    - 'Global Namespace': 'developer/namespace.md'
    - 'Entrada ACL': 'developer/entrada-acl.md'
    - 'Authentication Methods': 'developer/authentication-methods.md'
- 'Upgrade Guides':
    - 'Upgrading to Entrada ME 1.10': 'upgrade/1.10.md'
    - 'Upgrading to Entrada ME 1.11': 'upgrade/1.11.md'
- 'Support':
    - 'Overview': 'support/overview.md'
    - 'Knowledge Base': 'support/kb.md'
    - 'Developer FAQ': 'support/faq.md'
- 'License': 'about/license.md'

