site_name: Entrada Documentation
repo_url: https://github.com/EntradaProject
theme: readthedocs
pages:
- 'Home': 'index.md'
- 'Reporting Issues': 'about/reporting-issues.md'
- 'Administrator Documentation':
    - 'Server Requirements': 'administrator/server-requirements.md'
    - 'Application Server': 'administrator/application-server.md'
    - 'Database Server': 'administrator/database-server.md'
- 'Developer Documentation':
    - 'Getting Started': 'developer/getting-started.md'
    - 'Overview': 'developer/overview.md'
    - 'Quickstart Guide': 'developer/quickstart.md'
    - 'Entrada Walkthrough' : 'developer/walkthrough.md'
    - 'Coding Standards': 'developer/standards.md'
    - 'QA Standards': 'developer/qa-standards.md'
    - 'QA Tasks': 'developer/qa-tasks.md'
    - 'Database': 'developer/database.md'
    - 'Global Namespace': 'developer/namespace.md'
    - 'Entrada ACL': 'developer/entrada-acl.md'
    - 'Authentication Methods': 'developer/authentication-methods.md'
    - 'Developer FAQ': 'developer/faq.md'
- 'License': 'about/license.md'
